# データ
data_root: ./datasets/training_set/training_set
validation_split: 0.2
random_state: 42

# 前処理
image_size: 224
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# 学習
batch_size: 32
epochs: 10
learning_rate: 3e-4
weight_decay: 1e-4

# モデル
model_name: resnet18

# Optimizer
optimizer: adamw 

# Scheduler
scheduler: cosine   # "step", "plateau", "cosine" など
step_size: 5        # StepLR用
gamma: 0.1          # StepLR用
t_max: 10           # CosineAnnealingLR用